# Generated by Django 3.1 on 2021-03-18 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210318_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
    ]
