# Generated by Django 3.1 on 2021-03-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='reset_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
