# Generated by Django 3.2.3 on 2021-05-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_reply_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
