# Generated by Django 3.1 on 2021-03-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.PositiveSmallIntegerField(choices=[(1, 'exams'), (4, 'books'), (5, 'lectures'), (3, 'tutorials'), (2, 'assignment'), (6, 'other')], default=6)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'software'), (2, 'mechanical'), (3, 'civil'), (4, 'chemical'), (5, 'electrical'), (6, 'it'), (7, 'biomed'), (8, 'other')], default=8)),
                ('resource_file', models.FileField(blank=True, default=False, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
