# Generated by Django 3.1 on 2021-04-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resources_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
