# Generated by Django 3.1 on 2021-04-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resources_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
