# Generated by Django 3.1 on 2021-04-08 12:04

from django.db import migrations, models
import resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20210408_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_file',
            field=models.FileField(blank=True, default=False, null=True, upload_to=resources.models.resource_directory_path),
        ),
    ]
